### ISSUE TITLE
I need a little help, don't know how to do this.

### ISSUE THREAD

**Issue by unfoundedrevenge** [mrdanielps/r3Ddragon#10]
Hi! I'm fairly new to the modding scene, and to be perfectly candid anything and everything I do to mod my 3DS, is done nearly exclusively through guides and whatnot. I struggle on my own in this department.

I'm extremely interested in this emulator, but I can't seem to get it to work. I have a couple roms on my SD card, in a file named /vb/. When I open r3ddragon, it tells me it can't find the rom. Somebody else had posted a similar issue here, getting the same error code as me. I know that roms have to go in /vb/, but where is /vb/ itself supposed to go? Or am I doing something else wrong? Sorry if these questions are stupid. Thank you for any help.

**Comment by unfoundedrevenge** [comment]
I haven't been able to find anything helpful on the matter online.

**Comment by unfoundedrevenge** [comment]
I'm sorry. I guess I figured it out almost immediately after posting. Although I am still having some issues. I have, right now, Galactic Pinball and Wario Land. Galactic Pinball is extremely slow unless I have it skip 2 or 3 frames, but it'll crash after losing my ball upon starting a game. Wario Land will load the note about the instruction booklet, but seems to crash directly after. I don't know what I've done wrong.

**Comment by mrdanielps** [comment]
Closing because I'm no longer maintaining this project. Check out [Red Viper](https://github.com/skyfloogle/red-viper), it should fix the issues you experienced.
