### ISSUE TITLE
I'm sorry to bother but one file question...

### ISSUE THREAD

**Issue by MrHomeBrewuser** [mrdanielps/r3Ddragon#5]
What file type does this run? I tried vb and 7z but it froze
I'll admit I'm very new to homebrew but use it a ton

**Comment by MrHomeBrewuser** [comment]
You can choose not to reply to this if you want. I completely understand

**Comment by mrdanielps** [comment]
If it crashes after selecting a ROM, you're probably on an unsupported fw version. The 3dsx doesn't work on 9.3+.

Feel free to reopen the issue if that's not the problem.
