### ISSUE TITLE
display is just broken

### ISSUE THREAD

**Issue by mr2meowsYT** [mrdanielps/r3Ddragon#8]
random text and ascii to make up the sprites

**Comment by gingerbeardman** [comment]
Which game?

**Comment by DuckReconMajor** [comment]
I am seeing this on Mario Tennis. Also no sound. Haven't tried another game yet, when I tried to toggle sound it crashed

**Comment by DuckReconMajor** [comment]
[crash_dump_00000002.zip](https://github.com/mrdanielps/r3Ddragon/files/6987283/crash_dump_00000002.zip)

Saw it also on Wario Land Virtual Boy. Sound worked on Wario Land, but all the displayed graphics were glitchy. Wario Land crashed pretty quickly, though. Here are the crash dumps for Tennis and Wario Land

I am on a New 3ds XL

**Comment by mr2meowsYT** [comment]
This is 2 years old I guess my dumb ass forgor 💀 to close this
